"""
app/models/actions.py
──────────────────────
SQLModel ORM model for the 'actions' table.
Stores every response action generated by the Planning Agent
for a confirmed flood incident.

type values   : ALERT_CITIZENS | REROUTE_TRAFFIC | DISPATCH_DRAINAGE
status values : PENDING → SENT → ACTIVE → ON_SITE → COMPLETED
"""

import uuid
from datetime import datetime
from typing import Optional, Dict, Any
from sqlmodel import SQLModel, Field, Column, JSON


class Action(SQLModel, table=True):
    """
    Table 4: Response actions created by the Planning Agent.

    Each row represents one discrete action dispatched in response to
    a confirmed incident. Linked by a non-nullable incident_id FK.
    """
    __tablename__ = "actions"

    id: uuid.UUID = Field(
        default_factory=uuid.uuid4,
        primary_key=True,
        index=True,
        nullable=False
    )

    # ── Foreign key (non-optional — actions always belong to a confirmed incident)
    incident_id: uuid.UUID = Field(
        index=True,
        description="FK to incidents.id — always required; actions only exist for confirmed incidents"
    )

    # ── Action classification ──────────────────────────────────────────────────
    type: str = Field(
        description="'ALERT_CITIZENS' | 'REROUTE_TRAFFIC' | 'DISPATCH_DRAINAGE'"
    )

    # ── Lifecycle status ───────────────────────────────────────────────────────
    status: str = Field(
        default="PENDING",
        description="'PENDING' | 'SENT' | 'ACTIVE' | 'ON_SITE' | 'COMPLETED'"
    )

    # ── Planning Agent output ─────────────────────────────────────────────────
    predicted_side_effects: Optional[str] = Field(
        default=None,
        description="Free-text side-effect prediction from Planning Agent"
    )

    # ── Structured metadata (routing info, zone list, etc.) ───────────────────
    metadata: Optional[Dict[str, Any]] = Field(
        default=None,
        sa_column=Column(JSON)
    )

    # ── Timestamps ────────────────────────────────────────────────────────────
    updated_at: datetime = Field(
        default_factory=datetime.utcnow,
        nullable=False
    )
