#!/usr/bin/env bash
# Setup script for BloodLink API integration (frontend)

set -e

# Install required npm packages
npm install axios @tanstack/react-query @tanstack/react-query-devtools

# Create TypeScript source folders
mkdir -p src/api/client src/api/endpoints src/hooks/queries

# Create placeholder files
cat > src/api/client/apiClient.ts <<'EOF'
// Placeholder – actual implementation generated by Claude Code skill
EOF

cat > src/api/endpoints/donorApi.ts <<'EOF'
// Placeholder – donor API functions will be added here
EOF

cat > src/api/endpoints/bloodRequestApi.ts <<'EOF'
// Placeholder – blood request API functions will be added here
EOF

cat > src/hooks/queries/useNearbyDonors.ts <<'EOF'
// Placeholder – useNearbyDonors hook will be added here
EOF

cat > src/hooks/queries/useBloodRequests.ts <<'EOF'
// Placeholder – blood request hooks will be added here
EOF

cat > src/hooks/queries/useDonorProfile.ts <<'EOF'
// Placeholder – donor profile hook will be added here
EOF

echo "Setup complete. Next steps:"
echo "1. Review the generated files in src/"
echo "2. Replace placeholder content with the implementations from the .agent/skills/api-integration directory."
